OPENEUROPA-2943: Upgrade to PHP 7.3.
openeuropa/behat-transformation-context pull request #14
Opened 2020-03-19 17:10 UTC by sergepavle

2020-03-24 13:36 UTC, nagyad submitted a review, later dismissed

2020-03-25 14:49 UTC, ademarco requested changes
Let's not do this here, we don't need to have PHP 7.2 to run this, this is a general library that works with any PHP greater than 5.6, so we are ok.

2020-03-25 14:58 UTC, ademarco commented
Reopening, after internal discussion we will do this.

2020-03-26 08:09 UTC, 22Alexandra approved these changes

2020-03-26 16:51 UTC, imanoleguskiza approved these changes

2020-03-30 13:10 UTC, ademarco approved these changes

2020-03-30 13:10 UTC, merged