EWPP-516: Update docker php image.
openeuropa/behat-transformation-context pull request #16
Opened 2020-11-13 14:24 UTC by 22Alexandra

2020-11-17 17:04 UTC, sergepavle approved these changes, later dismissed

2020-11-18 14:28 UTC, nagyad submitted a review, later dismissed

2020-11-19 14:48 UTC, brummbar requested changes

2020-11-19 14:48 UTC, brummbar commented on .drone.yml
> +    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}
The PHP_VERSION variable shouldn't be touched, we should do like in here:
https://github.com/openeuropa/multivalue_form_element/pull/1/files#diff-b54b39f1afced2465e1f3641db9d5bbf4f3a7fcf890996dfedd3c197bcb7f8c7R7

```suggestion
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
```

2020-11-25 14:48 UTC, sergepavle approved these changes

2020-11-25 16:06 UTC, nagyad approved these changes

2020-11-27 13:48 UTC, brummbar approved these changes

2020-11-27 13:48 UTC, merged