OPENEUROPA-595: Move the TransformationContext to its own repository
openeuropa/behat-transformation-context pull request #2
Opened 2018-06-28 12:37 UTC by dxvargas

2018-06-28 13:59 UTC, imanoleguskiza requested changes

2018-06-28 13:59 UTC, imanoleguskiza commented on README.md
> +You can check included tests to see examples on how to use this context.
I think we should add a "Usage" section where we explain how to use the extension in a project: adding it to composer, adding the context in the behat yml, an example configuration etc. We have been doing it in all other components so far

2018-06-28 13:59 UTC, imanoleguskiza commented on README.md
> +This package makes available a Context allowing to transform human readable labels to selectors or page paths.
The phrasing is a bit weird, I think it would be best to say "This package provides a Behat context...""

2018-07-02 15:02 UTC, voidtek approved these changes

2018-07-03 08:59 UTC, imanoleguskiza approved these changes

2018-07-03 10:22 UTC, merged