OPENEUROPA-774: Relax dependencies
openeuropa/behat-transformation-context pull request #5
Opened 2018-09-11 12:16 UTC by voidtek

2018-09-12 09:02 UTC, dxvargas approved these changes

2018-09-12 12:14 UTC, dxvargas requested changes
It's missing the update of README for cp docker-compose.yml.dist

2018-09-12 12:34 UTC, richardcanoe submitted a review, later dismissed
👍

2018-09-13 13:47 UTC, dxvargas submitted a review, later dismissed

2018-09-13 13:57 UTC, dxvargas approved these changes

2018-09-13 14:13 UTC, richardcanoe approved these changes

2018-09-13 14:13 UTC, merged